[package]
name = "clinews"
version = "0.1.0"
edition = "2021"

description = "A simple cli news reader app"
license = "MIT"
authors = ["Jabooby"]

[dependencies]
colour = "2.1.0"
dotenv = "0.15.0"
termimad = "0.29.4"
cargo-deb = "2.4.0"
crossterm = "0.27.0"
newsapi = {path = "./newsapi"}